import { SectionWrapper } from '@/components/marketing/SectionWrapper';
import { AnimatedContainer } from '@/components/marketing/AnimatedContainer';

export const metadata = {
  title: 'Terms of Service | Aegis Sentinel',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-950 pt-32 pb-20">
      <SectionWrapper>
        <div className="max-w-3xl mx-auto">
          <AnimatedContainer animation="fade-up">
            <h1 className="text-4xl md:text-5xl font-bold text-slate-100 mb-8">Terms of Service</h1>
            <p className="text-slate-400 mb-10">Last updated: March 2026</p>
            
            <div className="prose prose-invert prose-slate max-w-none">
              <h2 className="text-2xl font-semibold text-slate-200 mt-8 mb-4">1. Legal Agreement</h2>
              <p className="text-slate-400 mb-6 leading-relaxed">
                This document is an electronic record in terms of the <strong>Information Technology Act, 2000</strong> and rules made thereunder. 
                By accessing or using the Aegis Sentinel Platform, you agree to be bound by these Terms of Service. This electronic record is generated by a computer system and does not require any physical or digital signatures.
              </p>
              
              <h2 className="text-2xl font-semibold text-slate-200 mt-8 mb-4">2. Compliance & Obligations</h2>
              <p className="text-slate-400 mb-6 leading-relaxed">
                You agree to use Aegis Sentinel strictly for legitimate security monitoring of your own cloud infrastructure. 
                You acknowledge that you must comply with all applicable Indian cyber laws, including but not limited to the directives issued by the Ministry of Electronics and Information Technology (MeitY) and the National Critical Information Infrastructure Protection Centre (NCIIPC), where applicable.
              </p>
              
              <h2 className="text-2xl font-semibold text-slate-200 mt-8 mb-4">3. Prohibited Conduct</h2>
              <p className="text-slate-400 mb-6 leading-relaxed">
                Under Section 43, 66, and other relevant chapters of the IT Act, 2000, you are strictly prohibited from reverse engineering our Python Engine, 
                testing our backend beyond authorized limits without explicit Bug Bounty approval, or utilizing our automated remediation tools to disrupt or deny services to unauthorized third parties.
              </p>

              <h2 className="text-2xl font-semibold text-slate-200 mt-8 mb-4">4. Governing Law & Jurisdiction</h2>
              <p className="text-slate-400 mb-6 leading-relaxed">
                These Terms shall be interpreted in accordance with the laws of the Republic of India. Any disputes arising out of these terms will be subject to the exclusive jurisdiction of the competent courts of Pune, Maharashtra.
              </p>
            </div>
          </AnimatedContainer>
        </div>
      </SectionWrapper>
    </div>
  );
}
